"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import django_heroku
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'es#5sv4@flq-*6+kk&_)2q&pncww2a=6(arwpei+n#bii2ejy%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    'coupons',
    'rosetta',
    'defender',
    'parler',
    'localflavor',
    'storages',
]



MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'defender.middleware.FailedLoginMiddleware',

]


ROOT_URLCONF = 'myshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'd1c9eohsp3ku04',
        'PASSWORD': '953f25bc2e0800a57a9c25bf69b62a12d86069c27162b880d849281b70463aa3',
        'USER': 'qvclipmdcuyggs',
        'HOST': 'ec2-54-242-43-231.compute-1.amazonaws.com',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = (
    ('en', _('English')),
    ('es', _('Spanish')),
)

LOCALE_PATHS = (
os.path.join(BASE_DIR, 'locale/'),
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


#
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'image/')

CART_SESSION_ID = 'cart'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# CELERY_BROKER_URL="redis://:p5a5f1a9f8dc10eab55c95494ffab4734e2ae00b7b770f2d2e141a5f389e68d70@ec2-54-197-141-216.compute-1.amazonaws.com:11800"
# CELERY_PASSWORD="p5a5f1a9f8dc10eab55c95494ffab4734e2ae00b7b770f2d2e141a5f389e68d70"
# CELERY_HOST="ec2-54-197-141-216.compute-1.amazonaws.com"
# Activate Django-Heroku.
django_heroku.settings(locals())
#
import braintree

#Braintree settings
BRAINTREE_MERCHANT_ID = 'y3vkmjrjjvw57zqr'
BRAINTREE_PUBLIC_KEY = 'bzt4mxvqyhnqk489'
BRAINTREE_PRIVATE_KEY = 'b5fcf9f381e24d405d6bcbcdcf3d0d76'



BRAINTREE_CONF = braintree.Configuration(
    braintree.Environment.Sandbox,
    BRAINTREE_MERCHANT_ID,
    BRAINTREE_PUBLIC_KEY,
    BRAINTREE_PRIVATE_KEY
)


PARLER_LANGUAGES = {
None: (
    {'code': 'en'},
    {'code': 'es'},
    ),
    'default': {
    'fallback': 'en',
    'hide_untranslated': False,
    }
}


AWS_ACCESS_KEY_ID = "AKIA3NG7K4GZR55H7CY5"
AWS_SECRET_ACCESS_KEY = "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"
AWS_STORAGE_BUCKET_NAME = "shoponlineawsbucket"

AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

AWS_LOCATION = 'static'
AWS_LOCATION_MEDIA = 'products'
AWS_S3_MAX_MEMORY_SIZE ='2'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
# STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)

MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION_MEDIA)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


REDIS_HOST = 'redis-19198.c263.us-east-1-2.ec2.cloud.redislabs.com'
REDIS_PASSWORD = 'PsbbRajcbgbnFxSrvCnqXYobn966lhkE'
REDIS_PORT = 19198
REDIS_DB = 0








